/** A role used by Atlas's provider-neutral conversation format. */
export type ChatRole = 'system' | 'user' | 'assistant' | 'tool';

/** A structured function call requested by a model. */
import type { StreamEvent } from './stream-events.js';

export interface ToolCall {
  /** Provider-generated call identifier. */
  id: string;
  /** Tool function name. */
  name: string;
  /** Decoded JSON arguments. */
  arguments: Record<string, unknown>;
}

/** JSON-schema description of a tool exposed to a model. */
export interface ToolDefinition {
  /** Stable tool name. */
  name: string;
  /** Model-visible description without internal permission rules. */
  description: string;
  /** JSON schema for the tool arguments. */
  parameters: Record<string, unknown>;
}

/** One provider-neutral message in a conversation. */
export interface ChatMessage {
  /** Author of the message. */
  role: ChatRole;
  /** Plain-text message content. */
  content: string;
  /** Tool calls requested by an assistant message. */
  toolCalls?: ToolCall[];
  /** Provider call identifier for a tool result message. */
  toolCallId?: string;
  /** Whether a tool result represents an execution error. */
  isError?: boolean;
}

/** Provider-neutral parameters for a chat completion. */
export interface ChatCompletionRequest {
  /** Ordered messages, including any system instruction. */
  messages: readonly ChatMessage[];
  /** Provider-specific model identifier. */
  model: string;
  /** Maximum number of tokens the provider may generate. */
  maxTokens?: number;
  /** Sampling temperature accepted by supported provider APIs. */
  temperature?: number;
  /** Requests token streaming when `true`. */
  stream?: boolean;
  /** Tools the model may call through structured tool requests. */
  tools?: ToolDefinition[];
  /** Provider tool-selection behavior. */
  toolChoice?: 'auto' | 'none';
  /**
   * Cancels the request when aborted.
   *
   * Used by the REPL so Ctrl+C can interrupt a turn instead of killing the
   * process and losing the conversation.
   */
  signal?: AbortSignal;
}

/** Token accounting reported by a provider, when available. */
export interface CompletionUsage {
  /** Tokens consumed by the request. */
  inputTokens: number;
  /** Tokens generated by the model. */
  outputTokens: number;
}

/** Normalized, non-streaming chat completion result. */
export interface ChatCompletionResponse {
  /** Assistant text returned by the model. */
  content: string;
  /**
   * Why the reply was empty, when it was.
   *
   * Empty turns are otherwise indistinguishable from the assistant choosing
   * to say nothing, which makes provider quirks very hard to diagnose.
   */
  emptyReason?: string | undefined;
  /**
   * Reasoning the model produced, when it reported any.
   *
   * Kept separate from `content` on purpose. Merging it in is how a thinking
   * model ends up showing its monologue instead of an answer.
   */
  reasoning?: string;
  /** Model identifier reported by the provider. */
  model: string;
  /** Token usage, when reported by the provider. */
  usage?: CompletionUsage;
  /** Provider-specific stop reason, normalized only to a string. */
  stopReason?: string;
  /** Structured tool calls requested by the assistant. */
  toolCalls?: ToolCall[];
}

/** Stable provider contract consumed by the CLI and library consumers. */
export interface LLMProvider {
  /** Stable Atlas provider identifier. */
  readonly name: string;

  /** Requests one complete, non-streaming chat completion. */
  chatCompletion(
    request: ChatCompletionRequest,
  ): Promise<ChatCompletionResponse>;

  /** Requests a chat completion and yields assistant text incrementally. */
  streamChatCompletion?(request: ChatCompletionRequest): AsyncIterable<string>;

  /**
   * Streams a whole turn as structured events.
   *
   * Unlike `streamChatCompletion`, this supports tools: narration arrives as
   * `text` events in real time, while tool-call fragments are buffered and
   * surfaced only as complete `tool_calls` events. A provider that cannot
   * stream tools leaves this undefined and callers fall back to
   * `chatCompletion`.
   */
  streamChatTurn?(request: ChatCompletionRequest): AsyncIterable<StreamEvent>;
}

/** Result returned by a tool executor to the provider loop. */
export interface ToolExecutionResult {
  /** Text result supplied back to the model. */
  content: string;
  /** Whether the tool result represents a failure. */
  isError?: boolean;
}

/** Harness-owned executor for model-requested tools. */
export interface ToolExecutor {
  /** Executes one validated tool call. */
  execute(toolCall: ToolCall): Promise<ToolExecutionResult>;
}

/** Injectable network and timeout settings for provider adapters. */
export interface ProviderDependencies {
  /** Fetch implementation, primarily useful for tests and custom runtimes. */
  fetch?: typeof globalThis.fetch | undefined;
  /** Request timeout in milliseconds. */
  timeoutMs?: number | undefined;
  /** Number of retries after a transient network or HTTP failure. */
  maxRetries?: number | undefined;
  /** Base delay for transient retries in milliseconds. */
  retryDelayMs?: number | undefined;
}
